### ISSUE TITLE
Uploading local files: Visual Issue

### ISSUE THREAD

**Issue by annieechen** [cs50/ide50#10]
![image](https://cloud.githubusercontent.com/assets/15977250/18038058/5eeb12b6-6d60-11e6-8f9f-eeabd92d9901.png)

(I wasn't sure this was the correct repo, please let me know to move this if it should be on another repo)

When using File-> Upload Local Files, there's an issue where the progress bar is hidden at the top of the screen. I let it upload for around 3 minutes, and then tried to cancel, but the bar is stuck at the top of the screen.

**Comment by kzidane** [comment]
Thanks for reporting, @annieechen! Afraid not the correct repo though! So closing this and will follow up via email, and maybe help open another issue in the correct repo!
