### ISSUE TITLE
Can't connect services

### ISSUE THREAD

**Issue by ifvictr** [cs50/ide50#11]
When using the CS50 IDE, I can't connect services like GitHub to my account like I can on Cloud9. Every time I click "Connect", it'll just redirect me back to [Cloud9](https://c9.io)'s login page, and not the application authorization.

**Comment by kzidane** [comment]
So when you click *CS50 IDE > Go To Your Dashboard* on the top-left, then *Repositories* on the left, then *Connect* next to GitHub, you get redirected to C9's login page, and not GitHub's (or asked to authorize C9 on GitHub, if already logged in to the latter?)

**Comment by ifvictr** [comment]
@kzidane Exactly. I think the IDE is still using Cloud9's app on GitHub. I do not have an account on [Cloud9](https://c9.io), and I'm pretty sure you won't need one (since we're using this IDE already). A solution to the current problem would be to create a new app, this one under CS50, instead of C9's, because the callback url would always lead back to C9.

**Comment by kzidane** [comment]
Ah. I see. Thanks for reporting! Will let you know as soon as this is fixed.

**Comment by dmalan** [comment]
@AnnaTiana, exactly what command were you typing? @brianyu28

**Comment by AnnaTiana** [comment]
~/workspace/pset3/find/ $ submit50 find
HTTP Error 404: Not Found
Invalid problem. Did you mean to submit something else?
Submission cancelled.

**Comment by dmalan** [comment]
Are you doing CS50x? Be sure to follow http://docs.cs50.net/2017/x/psets/3/pset3.html!

**Comment by AnnaTiana** [comment]
Thank you) It works for me))

**Comment by nadeemdada** [comment]
Getting an error in submitting cs50 week2 problems .
I have tried  submit50 initials , submit50 2017/x/initials.
Please help..
HTTP Error 404: Not Found
Invalid problem. Did you mean to submit something else?
Submission cancelled.

**Comment by brianyu28** [comment]
Hey @nadeemdada, be sure to follow the ["How to Submit"](http://docs.cs50.net/2017/x/psets/2/pset2.html#step-3-of-4) instructions exactly. For `initials`, you'll need to submit based on whether you completed the less-comfortable or the more-comfortable version of the problem, with either:
```
$ submit50 2017/x/initials/less
```
or
```
$ submit50 2017/x/initials/more
```

**Comment by nadeemdada** [comment]
Thank you sir @brianyu28.
It worked.

**Comment by omarubilla** [comment]
@brianyu28 hi this still did not work, is something not updated properly?

**Comment by brianyu28** [comment]
Hey @omarubilla, the submission instructions have changed a little recently. Be sure to submit with:

```
$ submit50 cs50/2017/x/initials/more
```

making sure to use the `cs50/` prefix.

**Comment by omarubilla** [comment]
Hi brian thanks for your reply- yup tried both doesn't work with/without prefix

**Comment by brianyu28** [comment]
Hm, can you show me what error is getting displayed when you run the command?

**Comment by omarubilla** [comment]
![screen shot 2017-08-16 at 9 05 37 am](https://user-images.githubusercontent.com/15100450/29373401-fee378d6-8262-11e7-9a40-b79be840a471.png)

**Comment by brianyu28** [comment]
Hm, can you type:

```
$ pip3 show submit50
```

and show me the output?

**Comment by omarubilla** [comment]
sure, 
i get nothing

**Comment by omarubilla** [comment]
i'm running it from same directory as shown above do I need to exit?

**Comment by brianyu28** [comment]
What version of the IDE are you running (you can find it in the upper-right corner of the screen)?

**Comment by omarubilla** [comment]
i believe its v81?

**Comment by omarubilla** [comment]
cloud9

**Comment by brianyu28** [comment]
Ah, looks like you're running an old version of CS50 IDE. Be sure to run:

```
$ update50
```

then close and re-open any terminal windows, then run `submit50` again!

**Comment by omarubilla** [comment]
ok I did that but i'll try again-is there a possibility its not updating correctly

**Comment by omarubilla** [comment]
after doing update50 it still shows v81 in the top corner

**Comment by brianyu28** [comment]
Hm, @kzidane, any thoughts on this one?

**Comment by omarubilla** [comment]
thanks I got it,
used: 
$ ~/.cs50/bin/update50

**Comment by GenevieDube** [comment]
Hi, my check50 is broken. Please can you explain me very detailed how I find the authorize application because I don,t find it. here is what I did : ~/workspace/pset4/recover/ $ check50 cs50/2017/x/recover
Connecting....
Authenticating.....
GitHub username: xxxx
GitHub password: *****************
Preparing.....
Looks like check50 isn't enabled for your account yet. Log into https://cs50.me/ in a browser, click "Authorize application", and re-run check50 here!
Submission cancelled.
When I'm log into the cs50 I see only my scores and submissions and in account I see only if I,m connect or disconnect. Please help me out !

**Comment by brianyu28** [comment]
Hey @GenevieDube, can you try running

```
$ check50 --verbose cs50/2017/x/recover
```

and let me know what the output is?

**Comment by GenevieDube** [comment]
actually none of check50 is working : here is the output with your suggestion : ~/workspace/pset4/recover/ $ check50 --verbose cs50/2017/x/recover                                                                             
Connecting...
Authenticating...
git config --global credential.https://github.com/submit50.username
git config --global credential.https://github.com/submit50.username
GitHub username: 

thks a lot for trying to help cause I can't finish anything now without check50 :(

**Comment by GenevieDube** [comment]
oh... then when I wanted to get back to pset here what happened next : 
GitHub username: Traceback (most recent call last):
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/submit50.py", line 485, in submit
    username, password = run("git config --global credential.https://github.com/submit50.username", quiet=True), None
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/submit50.py", line 358, in run
    raise Error()
submit50.Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pyenv/versions/3.6.0/bin/check50", line 11, in <module>
    load_entry_point('check50==2.0.1', 'console_scripts', 'check50')()
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/check50.py", line 85, in main
    username, commit_hash = submit50.submit("check50", identifier)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/submit50.py", line 498, in submit
    username, password, email = authenticate(org)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/submit50.py", line 179, in authenticate
    username = rlinput(_("GitHub username: "), username).strip()
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/submit50.py", line 167, in rlinput
    return input(prompt)
KeyboardInterrupt
Sorry, something's wrong! Let sysadmins@cs50.harvard.edu know!
git credential-cache --socket /home/ubuntu/.git-credential-cache/submit50 exit
git credential-osxkeychain erase
git: 'credential-osxkeychain' is not a git command. See 'git --help'.
host=github.com
protocol=https

**Comment by neelrajpatil** [comment]
Hi Could you help me get the Check50 to work for me?
I am able to submit the files but I can't run Check50 on them, when I do run it I get the following error.

<img width="1187" alt="screen shot 2017-08-27 at 5 34 16 pm" src="https://user-images.githubusercontent.com/19901671/29749621-fbef40ee-8b4d-11e7-9961-d9ef745ac23e.png">

**Comment by Moonybl** [comment]
I have the same problem as @neelrajpatil . My user name is Moonybl and I'm taking the course in edx. Is there anything I can do @dmalan ?? Thanks
