### ISSUE TITLE
why is it trying to modify permissions for all files in my mac?

### ISSUE THREAD

**Issue by MrDebugger** [cs50/ide50#11]
<img width="1051" alt="image" src="https://github.com/cs50/ide50/assets/25988388/6a18858f-ab69-400f-a3bf-5de144ec51a2">

**Comment by rongxin-liu** [comment]
It is modifying the content of the container, not your Mac. Also, ide50 has been deprecated.

Please use Codespace:
https://cs50.readthedocs.io/code/#offline-with-docker

**Comment by MrDebugger** [comment]
@rongxin-liu image downloading in the middle when connection is slow or disconnected. Unlike docker pull the dev container doesn't resume.
