### ISSUE TITLE
can't authorize "Authorize application" for my account

### ISSUE THREAD

**Issue by venciso495** [cs50/ide50#119]
can't authorize "Authorize application" for my account. When I try to use check50 and Authorize application online the website will not allow me to press the authorize submit button

**Comment by dmalan** [comment]
What OS and browser are you using? And can you attach a screenshot of what you see?

**Comment by venciso495** [comment]
I am using OS X 10.8.5 and Google Chrome.

**Comment by venciso495** [comment]
I don't think I can attach a screen shot to this message or I did and I can't tell.

**Comment by brianyu28** [comment]
Hey @venciso495, what do you see when you go to CS50.me (and after you've typed in your GitHub username and password, if prompted)?

**Comment by venciso495** [comment]
I see a page that heads Authorize CS50.me
Then my id picture with side text stating: CS50.me by submit50 wants to access you venciso495 account
below that: Personal user data Email Addresses(read-only)
then the green button Authorize submit50 ... but the button is faded as if it was already pushed. I can't click on the button.

**Comment by venciso495** [comment]
Is this because Github no longer supports my version of chrome? I am not able to update my browser anymore. Would this be a problem?

**Comment by brianyu28** [comment]
Can you try a different web browser (e.g. Safari)? Does that allow you to authorize the application?

**Comment by venciso495** [comment]
I have tried but its the same problem. My safari is too old and I can't update it.

**Comment by dmalan** [comment]
@venciso495, is JavaScript disabled in your browser? If so, see https://help.github.com/articles/supported-browsers/ for GitHub's supported browser versions.
