### ISSUE TITLE
check50 error

### ISSUE THREAD

**Issue by warren-tarditi** [cs50/ide50#131]
![image](https://user-images.githubusercontent.com/31476875/29996308-b4269286-8ffc-11e7-9c4e-a7f8da512083.png)

I can't seem to run check50 as it tells me I'm missing the required files. This is confusing as i have already set up and saved the files (in this case water.c). I also can't check50 the previous file hello.c, when I could do it before.
Any suggestions?

**Comment by kzidane** [comment]
It appears your `water.c` is in `~/workspace/pset1/` not in `~/workspace/`. You should run `cd ~/workspace/pset1/` first, then try `check50` again per the instructions.

**Comment by warren-tarditi** [comment]
thanks for the suggestion. it worked :)
