### ISSUE TITLE
~cs50/hacker1/credit doesn't reflect source of staff solution

### ISSUE THREAD

**Issue by glennholloway** [cs50/ide50#133]
As pointed out by an edX student (https://app.frontapp.com/open/cnv_795uoh), the binary `~cs50/hacker1/credit` shipped with **ide50** hangs when its user types in something other than a long int. [The source](https://github.com/cs50/solutions/blob/master/2016/fall/problems/credit/0/credit.c) works fine.

**Comment by kzidane** [comment]
https://github.com/cs50/ide50/pull/134

Running the rest of staff solutions under `pset*` and `hacker*` to recompile any others as needed before releasing v113.

**Comment by kzidane** [comment]
Should be fixed by running `update50`!
