### ISSUE TITLE
Permission Denied!

### ISSUE THREAD

**Issue by kalikasharma8942** [cs50/ide50#143]
![permission denied](https://user-images.githubusercontent.com/31867533/30299865-5fa7ec6c-976f-11e7-9a2d-06126e7b8bd6.jpg)
I was able to run my code successfully the first time but then I am stuck here while I try to re-run another file or the same file again. Can someone please help with this?

**Comment by kzidane** [comment]
It seems you're trying to run a source file not an executable. You should compile your program first, then run the result executable file!

**Comment by kalikasharma8942** [comment]
Thank you for the quick response. I tried compiling it but no help.

**Comment by kzidane** [comment]
Would love to look further into that and try to help, but it's generally best to post these sort of questions with transcript/screenshot as necessary to any of our discussion forums per https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/a7ec0c0a7b6e460f877da0734811c4cd/! :wink:

**Comment by kalikasharma8942** [comment]
Thank you so much for your help. I was able to do it :) Thanks again.
