### ISSUE TITLE
Add auto-sharing to course staff

### ISSUE THREAD

**Issue by benedictbrown** [cs50/ide50#156]
It would be nice if students' IDEs were auto-shared to the relevant course staff.  It looks like this could be done via the c9.ide.collab module which provides

workspace.addMember() and workspace.removeMember()

Access controls seem to be "r" and "rw".

The basic idea would be to have the IDE connect to our server periodically (e.g. on startup, on running update50, once-per-day, or when a share50 command is run) to retrieve the list of staff who should have access to the IDE.  It would be shared with those staff, and any other users could be removed (or course heads could be alerted).  Permitted staff could be all course staff from the student's school (easy), or a rotating list (e.g. the staff that is currently available in office hours and/or a rotating list of staff who are currently responsible for monitoring CS50 Discourse).  In at least the latter case, we would also need a mechanism to manually add/remove staff from the share list for a particular student's workspace.

Back-end database design to support non-static sharing is easy.  C9 code to adjust the sharing should be very easy, even factoring in preventing the script from keeping the workspace alive unnecessarily and jittering connection times so everyone isn't updating there sharing at the same time.  Creating a GUI to update who has access to which IDEs may be a pain.

**Comment by dmalan** [comment]
Emailed!

**Comment by benedictbrown** [comment]
I think the API already supports this, although we'd have to write our own plugin to implement the auto-sharing.  I can definitely see c9 not being comfy providing that as a standard feature.

Doug or one of the other staff said AP teachers have reported that being shared on everyone's workspace generated lots of requests from students to remotely look at and debug their code.  On the other hand, I'm starting to experiment with prescribing a coding process to struggling students and using the revision history to follow up with them on it.  And we're also using it to verify that students completed the code before the deadline when there are submission problems.
