### ISSUE TITLE
Self-updating update50?

### ISSUE THREAD

**Issue by kzidane** [cs50/ide50#18]
When updating `update50`, users need to run `update50` at least twice in order to benefit from this update. Is it worth adopting a self-updating mechanism? For example:

```
# have `update50` installed as `/tmp/update50`
if diff /tmp/udpate50 "$0"
    cp /tmp/update50 "$0"
    rm -f /tmp/update50
    "$0"
```

@dmalan @glennholloway

**Comment by glennholloway** [comment]
How often to we need to update `update50`? A temporary patch like that for `project.settings` can be added to the post-installation script for the `ide50*.deb` package.

**Comment by kzidane** [comment]
Not often I suppose. Just thought it might be good to have in general. And yeah, should've added to `postinst` instead, but realized too late. Sorry!

**Comment by ankitrgadiya** [comment]
A cronjob can be added which will run update50 in background after fixed intervals.

**Comment by kzidane** [comment]
We're `curl`ing `update50` now.
