### ISSUE TITLE
add `fuser -k 8080/tcp` to flask wrapper?

### ISSUE THREAD

**Issue by dmalan** [cs50/ide50#198]
To ensure other servers are killed, especially if the terminal windows got closed and the server orphaned?

**Comment by dmalan** [comment]
@kzidane do we do this already for `phpliteadmin` and `8082`? And with `http-server` and `8081`?

**Comment by kzidane** [comment]
If a terminal tab gets closed, all child processes are killed. Yes, we do this for `8081` and `8082`, but I thought we wanted to leave `8080` for the user?

**Comment by dmalan** [comment]
That doesn't always seem to happen reliably, though? Have definitely seen students with no terminal windows open but processes still running in the background (e.g., `flask`).

**Comment by kzidane** [comment]
Maybe open in a hidden console?

**Comment by dmalan** [comment]
With console still open, but no terminal windows therein! Has happened to me too!
