### ISSUE TITLE
Cannot submit water problem set 1

### ISSUE THREAD

**Issue by james2432** [cs50/ide50#224]
I was able to submit hello fine.
But everytime I try to submit water or check it I get:

```
 submit50 --verbose water/water.c
 Connecting...
 HTTP Error 404: Not Found
 Invalid slug. Did you mean to submit something else?
```
my current structure is ~/workspace/water/water.c

**Comment by kzidane** [comment]
Please read the submission instructions carefully from the specification and follow them!
