### ISSUE TITLE
Web Server not working with offline IDE v130

### ISSUE THREAD

**Issue by MadDogDean** [cs50/ide50#228]
I am running the offline CS50 IDE, version 130.

pset7 calls for running `flask run` and then, optionally, viewing the returned web app in a browser window by clicking `CS50 IDE > Web Server`. This however returns an error "Error opening workspace domain. Try reloading the IDE!"

Restarting the IDE, or Docker Toolbox (on Win7 x64) doesn't resolve the issue. 

However, following the URL does open the flask app in a browser window.

![ide50 v130](https://user-images.githubusercontent.com/23712335/33920974-09ec7376-dffc-11e7-863a-1812d6235896.jpg)

**Comment by kzidane** [comment]
Try running:

```
$ docker restart ide50
```

in the Docker QuickStart Terminal, reload the browser tab, and try again!

**Comment by MadDogDean** [comment]
Hi Kareem,

Tried that and also completely shutting down everything and restarting. I used Chrome, but in the morning I'll try Firefox and let you know.

Cheers,
Dean

**Comment by kzidane** [comment]
After restarting and reloading, do you see the version number on the top-left corner? Do you see any errors in the JavaScript console?

**Comment by MadDogDean** [comment]
You know, the version number in the top left corner seems hit & miss. Sometimes it shows, sometimes not. I don't see any errors, it just doesn't run. But having said that, I think it may have worked before the last update (but don't quote me on that, I just remember it working). In the morning I'll test some more and let you know.

Cheers
MadDogDean

**Comment by MadDogDean** [comment]
In true code fashion, it fixed itself this morning!
Actually, I think Chrome updated overnight, it is now at v63.0.3239.84, Win7 x64
The CS50 IDE version number displays correctly in the upper right corner and `CS50 IDE > Web Server` runs the flask app as expected.
This ticket is done!!
