### ISSUE TITLE
CS50 IDE is slow compared to Bare Ubuntu on c9

### ISSUE THREAD

**Issue by YoginthS** [cs50/ide50#252]
CS50 IDE is slow compared to Bare **Ubuntu OS** on c9! so what is the reason can we able to fix it? Typing in CLI with slow internet is bad with **Harvard IDE**

**Comment by kzidane** [comment]
If your connection is slow perhaps best would be to use the CS50 IDE Offline instead. See https://manual.cs50.net/ide/offline!

**Comment by YoginthS** [comment]
But Ubuntu is working fine for me on Cloud 9

**Comment by kzidane** [comment]
If you don't think your connection has a problem, I would suggest creating another Harvard's CS50 workspace. If the problem remains, I would contact support@c9.io with the issue.

**Comment by YoginthS** [comment]
fine
