### ISSUE TITLE
Cloud9 no longer includes /etc/sudoers.d by default

### ISSUE THREAD

**Issue by zosnap** [cs50/ide50#27]
This is the root cause of this issue which showed up for my students this morning: http://cs50.stackexchange.com/questions/22486/ubuntu-password-required-when-starting-apache-50-pset7%E2%80%8B

The /etc/sudoers file generated by Cloud9 looks like this:
```
# This file is overwritten by Cloud9 when a container is restarted, changes will not be kept.
Defaults        env_reset
Defaults        mail_badpass
Defaults        !secure_path

# User privilege specification
root    ALL=(ALL:ALL) ALL

# Members of the admin group may gain root privileges
%admin ALL=(ALL) ALL

# Allow members of group sudo to execute any command
%sudo ALL=NOPASSWD:ALL
```
Notice the absence of #includedir /etc/sudoers.d. This means that the line giving www-data permissions in /etc/sudoers.d/ide50 doesn't get executed and the sudo -u www-data line in the apache50 script prompts the user for a password. 

Not sure what makes the most sense as a workaround. I opened a bug with Cloud9 [here](https://community.c9.io/t/auto-generated-sudoers-file-doesnt-include-etc-sudoers-d/12226)

**Comment by kzidane** [comment]
Thanks for reporting, @zosnap! We'd already figured that out and it should be fixed asap!

**Comment by kzidane** [comment]
Should be fixed now!
