### ISSUE TITLE
Add a Python template to the File>New from Templates list?

### ISSUE THREAD

**Issue by curiouskiwi** [cs50/ide50#31]
Wondering if we could add a Python template to our existing ones.  Was thinking would be handy to have this format:

    #!/usr/bin/env python3
    
    import cs50
    
    def main():
    
    # TODO

    if __name__ == "__main__":
    main()

If that's too much, could just have the first line plus anything else deemed useful.

**Comment by kzidane** [comment]
Addressed per https://github.com/cs50/harvard.cs50.simple/issues/65! Thanks!

**Comment by dmalan** [comment]
Thanks, @curiouskiwi! Will deploy with our next release!

**Comment by curiouskiwi** [comment]
Thanks @kzidane and @dmalan for a quick response. 👍
