### ISSUE TITLE
apt caching

### ISSUE THREAD

**Issue by kzidane** [cs50/ide50#37]
My failed attempt to deploy `phpliteadmin` today revealed a potential scenario that we might want to protect our workspaces against. It looks like `apt` might cache some bad index files (e.g., `InRelease`, `Packages.gz`, etc), which would cause `apt-get update`, and therefore `update50`, to fail.

The typical solution to this is to remove everything under `/var/lib/apt/lists/`, before running `apt-get update`, to force `apt` to fetch new index files. (http://askubuntu.com/a/41618/207935)

If we're not comfortable removing index files for other `apt` repos, we might just remove our own, which start with `mirror.cs50.net`.

```
$ rm -rf /var/lib/apt/lists/mirror.cs50.net*
```

Thoughts, @dmalan @glennholloway?

**Comment by dmalan** [comment]
Removing our own seems reasonable, though does that slow down `update50`, if that effectively induces another `apt-get update`? Are we sure this isn't a CloudFront (CDN) issue, whereby not all newly updated files are propagating at the same time?

**Comment by kzidane** [comment]
> Removing our own seems reasonable, though does that slow down `update50`, if that effectively induces another `apt-get update`?

Why induce _another_ `apt-get update`? I think we could just remove before [`update50`#L25](https://github.com/cs50/ide50/blob/master/files/usr/bin/update50#L25)?

> Are we sure this isn't a CloudFront (CDN) issue, whereby not all newly updated files are propagating at the same time?

It could be, but won't harm to force that anyway? After all only a couple of files (a few kilobytes) get re-downloaded.

**Comment by dmalan** [comment]
Okay, sounds worth a try!

**Comment by kzidane** [comment]
Actually, looks like Dan added this already since v43 per 881faee!
