### ISSUE TITLE
after updating init.js and reloading, version # disappeared from top-right corner

### ISSUE THREAD

**Issue by dmalan** [cs50/ide50#51]
![screen shot 2017-07-01 at 2 47 58 pm](https://user-images.githubusercontent.com/788678/27764662-523603de-5e6c-11e7-848f-5ed82456a5c4.png)

**Comment by kzidane** [comment]
That's because pre-installed info plugin was disabled, but the new one wasn't installed correctly due to `npm` error. Fixed in your workspace. The plugin won't be built on users' workspaces anyway, so that shouldn't be a problem.
