### ISSUE TITLE
pip's cache

### ISSUE THREAD

**Issue by kzidane** [cs50/ide50#63]
A couple of times `pip`'s cache got into the way of the new update. Apparently, `render50`'s dependencies (e.g., `lxml`) refuse to build if there's a build directory already (e.g., `/tmp/pip_build_root/lxml`). Not quite sure what action caused this, but guessing might be that students hit Ctrl-C during the build step that takes long.

Manually removing `/tmp/pip_build_root/*` seems to fix the problem, but will google if there's a better way to clear `pip`'s cache.

**Comment by dmalan** [comment]
Resolved okay, @kzidane?

**Comment by kzidane** [comment]
Should be resolved, yes.
