### ISSUE TITLE
Sudo password for ide50 offline

### ISSUE THREAD

**Issue by swrjnthjr** [cs50/ide50#7]
How do I change or reset the password for `ubuntu` user in offline IDE?

**Comment by dmalan** [comment]
Afraid `sudo` is disabled, and there's no password!

**Comment by Goku-UI** [comment]
Wait... sudo is disabled in the IDE? I started fiddling around a bit and couldn't find it... I just wanted to see what was in the root folder.

**Comment by dmalan** [comment]
You can still `ls` in most directories, though!

**Comment by Goku-UI** [comment]
I also noticed that la (which is an abbreviation for ls -a) doesn't work, but ls -a does... why is this? Also, is .bash_history just default, or did you guys put it in there? The IDE's terminal is kind of like trying to remember something you did a long time ago. You know how to do some things, but there are other things you're certain you remember that don't work.

**Comment by anugrahmasih261** [comment]
hi dmalan first of all thanks a lot for teaching us so well we love you for this please assign someone to solve our problems too  I am trying to connect my projects with PostgreSQL  in online cs50ide but it is asking for ubuntu password which I am unable to find kindly guide me through

**Comment by anugrahmasih261** [comment]
if possible kindly reply to my mail anugrahmasih1012@icloud.com

**Comment by dmalan** [comment]
> I also noticed that la (which is an abbreviation for ls -a) doesn't work, but ls -a does... why is this? Also, is .bash_history just default, or did you guys put it in there?

`la` is a common "alias" for `ls -a` but not one we've included! And `.bash_history` is created after you've executed some number of commands!

**Comment by dmalan** [comment]
> it is asking for ubuntu password which I am unable to find kindly guide me through

Afraid `sudo` is disabled on CS50 IDE, so it's not possible to install software as `root`!

**Comment by anugrahmasih261** [comment]
Hey David thanks for reply
But my real query is how I can use PostgreSQL with django in course it was
not clearly mentioned they didn’t even tell us how we can configure post
gresql with django as they tough us how to connect with mysqlite3 they
should have tought us that how we can connect django with PostgreSQL I hope
you understand my problem as Jesus says believe what you ask and you will
be given I have that much trust in you hope to hear from you soon

**Comment by dmalan** [comment]
For project questions, best to reach out via any of https://cs50.harvard.edu/web/2020/communities/ so any of us can answer!

**Comment by OxOneBeing** [comment]
I'm trying to install Betty style for C in the terminal but it needed extra privileges. Seems I'm stuck now to learn that there is no support for sudo and passwords.

**Comment by rongxin-liu** [comment]
> I'm trying to install Betty style for C in the terminal but it needed extra privileges. Seems I'm stuck now to learn that there is no support for sudo and passwords.

sudo is disabled and there is no password. Please use the new IDE instead:

https://cs50.readthedocs.io/code/#with-docker

**Comment by OxOneBeing** [comment]
> > I'm trying to install Betty style for C in the terminal but it needed extra privileges. Seems I'm stuck now to learn that there is no support for sudo and passwords.
> 
> sudo is disabled and there is no password. Please use the new IDE instead:
> 
> https://cs50.readthedocs.io/code/#with-docker

Thank you for your response. However. the new IDE has git disabled.

**Comment by rongxin-liu** [comment]
> 

You can use git outside of your home directory.
