### ISSUE TITLE
disable contextual menu over Collaborate/Outline/Debugger panel in less-comfy mode

### ISSUE THREAD

**Issue by dmalan** [cs50/ide50#89]
To avoid accidental closures. 

<img width="328" alt="screen shot 2017-08-01 at 3 20 30 pm" src="https://user-images.githubusercontent.com/788678/28842825-291e19b8-76cd-11e7-8058-1e6d9dbb9ac5.png">

**Comment by dmalan** [comment]
And this one?

**Comment by kzidane** [comment]
Already implemented per https://github.com/cs50/harvard.cs50.simple/commit/f7613f2669ae44c58c2029dad1cfc58440e0813f. To be merged and included in today's PR.
