### ISSUE TITLE
pset6 staff solutions fail due to bad magic number in .pyc files

### ISSUE THREAD

**Issue by leviroth** [cs50/ide50#98]
E.g.:

```
~/workspace/ $ ~cs50/pset6/smile
RuntimeError: Bad magic number in .pyc file
```

This was reported on the CS50x Slack, and confirmed after running update50. Though I haven't investigated thoroughly, perhaps something to do with the fact that Python 3.6 was installed during that update?

Edit: Yes, it looks like the pyc files have the magic number from 3.4: https://github.com/google/pytype/blob/master/pytype/pyc/magic.py#L75

**Comment by dmalan** [comment]
Thanks, @leviroth!

**Comment by kzidane** [comment]
Thank you for reporting this, @leviroth! Should be fixed after running `update50`!
